site_name: "dream-trainer"
site_url: "https://dream3d-ml.github.io/dream-trainer"
site_description: "Dream Trainer"
site_author: "Dream3D"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/dream3d-ml/dream-trainer"
theme:
  name: shadcn
  pygments_style: "github-dark"

nav:
  - Welcome: index.md
  - install.md
  - extensions.md
  - Examples:
      - examples/a.md

plugins:
  - search # put it first to inject out custom code

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
    slugify:
      !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha: